name: Semantic Versioning

on:
  pull_request:
    types:
      - closed
    branches:
      - staging
      - prod

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history for versioning

      - name: Prevent Direct Merging to Prod (Only Allowed from Staging or Hotfix)
        run: |
          base_branch="${{ github.event.pull_request.base.ref }}"
          head_branch="${{ github.event.pull_request.head.ref }}"
          echo "Base Branch: $base_branch"
          echo "Head Branch: $head_branch"

          if [[ "$base_branch" == "prod" && "$head_branch" != "staging" && ! "$head_branch" =~ ^hot/ ]]; then
            echo "Error: Only staging or hotfix (hot/*) branches can be merged into prod!"
            exit 1
          fi

          if [[ "$base_branch" == "staging" && "$head_branch" != "develop" && ! "$head_branch" =~ ^bug/ ]]; then
            echo "Error: Only develop or bugfix (bug/*) branches can be merged into staging!"
            exit 1
          fi

      - name: Fetch Latest Tags
        run: |
          git fetch --tags --force
          git tag --list --sort=-v:refname  # Debugging: Show all tags sorted by version

      - name: Determine Semantic Version 
        run: |
          set -e  # Exit if any command fails
          base_branch="${{ github.event.pull_request.base.ref }}"
          pr_title="${{ github.event.pull_request.title }}"
          pr_body="${{ github.event.pull_request.body }}"
          #new_version="${{ steps.versioning.outputs.version }}"

          echo "Base Branch: $base_branch"
          echo "PR_TITLE: $pr_title"
          echo "PR_BODY: $pr_body"

          prerelease="false"
          latest_tag=$(git tag --list "v*" | sort -V | tail -n 1)
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "Latest Tag: $latest_tag"


          if [[ "$base_branch" == "staging" ]]; then
              echo "Generating RC version..."
              git fetch --tags  # Ensure all tags are fetched

              # Get the latest stable version (excluding RC versions)
              latest_stable_tag=$(git tag --list "v*" | grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$" | sort -rV | head -n 1)
              echo "latest_stable_version: $latest_stable_tag"

              if [[ -z "$latest_stable_tag" ]]; then
                  # No previous stable versions, start fresh
                  new_version="v1.0.0-rc.1"
              else
                  # Find the latest RC version for this stable version
                  latest_rc_tag=$(git tag --list | grep -E "^${latest_stable_tag}-rc.[0-9]+" | sort -V | tail -n 1)
                  echo "latest RC Version: $latest_rc_tag"

                  if [[ -n "$latest_rc_tag" ]]; then
                      # Extract the RC number using `sed` (cross-platform compatibility)
                      current_rc_number=$(echo "$latest_rc_tag" | sed -E 's/.*-rc\.([0-9]+)/\1/')
                      rc_number=$((current_rc_number + 1))
                      new_version="${latest_stable_tag}-rc.${rc_number}"
                  else
                      # No RC exists for the latest stable version, start with rc.1
                      new_version="${latest_stable_tag}-rc.1"
                  fi
              fi
              #setting prerelease true
              prerelease="true"
              echo "New RC Version: $new_version"
          fi

          if [[ "$base_branch" == "prod" ]]; then
            latest_rc_tag=$(git tag --list "v*-rc.*" | sort -V | tail -n 1)

            if [[ -n "$latest_rc_tag" ]]; then
              new_version="${latest_rc_tag%-rc.*}"
            fi

            last_version=$(git tag --list "v*" | sort -V | tail -n 1)
            echo "Latest Version: $last_version"
            major=$(echo "$last_version" | cut -d. -f1 | tr -d 'v')
            minor=$(echo "$last_version" | cut -d. -f2)
            patch=$(echo "$last_version" | cut -d. -f3)

            if echo "$pr_title" | grep -q "(MAJOR)" || echo "$pr_body" | grep -q "(MAJOR)"; then
              echo "Bumping major..."
              major=$((major + 1))
              minor=0
              patch=0
            elif echo "$pr_title" | grep -q "(MINOR)" || echo "$pr_body" | grep -q "(MINOR)"; then
              echo "Bumping minor..."
              minor=$((minor + 1))
              patch=0
            else
              echo "Bumping patch..."
              patch=$((patch + 1))
            fi
            new_version="v$major.$minor.$patch"
            prerelease="false"
          fi

          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "New Version: $new_version"
          echo "PRERELEASE=$prerelease" >> $GITHUB_ENV

      - name: Debug Version
        run: |
          echo "NEW_VERSION=${{ env.NEW_VERSION }}"

      - name: Push New Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ env.NEW_VERSION }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/bikkavj/ver_demo.git
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}

      - name: Fetch Latest Pre-release or Stable Tag
        run: |
          git fetch --tags

          # Get the two latest tags
          tags=$(git tag --list "v*" | sort -V | tail -n 2)

          # Assign the latest and previous versions
          new_version=$(echo "$tags" | tail -n 1)
          previous_tag=$(echo "$tags" | head -n 1)

          if [[ "$previous_tag" == "$new_version" ]]; then
            echo "Only one tag found, setting previous_tag to empty."
            previous_tag=""
          fi

          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "PREVIOUS_TAG=$previous_tag" >> $GITHUB_ENV
          echo "New Version: $new_version"
          echo "Previous Tag: $previous_tag"

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ env.NEW_VERSION }}
          PREVIOUS_TAG: ${{ env.PREVIOUS_TAG }}
        with:
          fromTag: ${{ env.PREVIOUS_TAG }}
          toTag: ${{ env.NEW_VERSION }}
          fetchViaCommits: true

      - name: Save Changelog to File
        run: |
          echo -e "Automated release for ${{ env.NEW_VERSION }}\n\n## Changelog\n## Uncategorized\n" > release_filter_notes.md
          echo "${{ steps.build_changelog.outputs.changelog }}" | sed '/^[[:space:]]*$/d' | tail -n 2 >> release_filter_notes.md


      - name: Debug Filtered Changelog
        run: |
          echo "Filtered Changelog:"
          cat release_filter_notes.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ env.NEW_VERSION }}
          PRERELEASE: ${{ env.PRERELEASE }}
          CHANGELOG: ${{ env.CHANGELOG }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}
          body_path: release_filter_notes.md
          prerelease: ${{ env.PRERELEASE }}

